apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: magento-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: magento-admin-static-ip
    networking.gke.io/managed-certificates: admin-certificate
spec:
  backend:
    serviceName: magento-admin
    servicePort: 80
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: admin-certificate
spec:
  domains:
    - admin.example.com
