apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: magento-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - image: asia.gcr.io/magento-gke-248206/magento:1
              name: magento
              resources:
                requests:
                  memory: 256Mi
                  cpu: 100m
              command:
                - /usr/local/bin/php
              args:
                - /var/www/html/bin/magento
                - list
