apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-static-pvc
spec:
  selector:
    matchLabels:
      type: nfs-static-pv
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-static-pv
  labels:
    type: nfs-static-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: /static/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-upload-pvc
spec:
  selector:
    matchLabels:
      type: nfs-upload-pv
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-upload-pv
  labels:
    type: nfs-upload-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: /upload/
