apiVersion: v1
kind: Service
metadata:
  labels:
    app: magento
  name: magento
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: magento
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento
  labels:
    app: magento
spec:
  replicas: 3
  selector:
    matchLabels:
      app: magento
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: magento
        tier: frontend
    spec:
      containers:
        - image: asia.gcr.io/magento-gke-248206/magento:1
          name: magento
          resources:
            requests:
              memory: 756Mi
              cpu: 200m
          ports:
            - containerPort: 80
              name: magento
          env:
            - name: MAGENTO_DB_HOST
              value: "10.125.192.3"
            - name: MAGENTO_DB_USER
              value: "root"
            - name: MAGENTO_DB_PASSWORD
              value: "password"
            - name: MAGENTO_REDIS_HOST
              value: "10.4.12.169"
          volumeMounts:
            - name: nfs-pvc
              mountPath: /var/www/html/pub/media/upload
      volumes:
        - name: nfs-pvc
          persistentVolumeClaim:
            claimName: nfs-pvc
