apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-ingress
  namespace: magento-ns
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  egress:
  - {}
---
# Magento は NodePort 経由の 8080 通信ポートを許可する
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: magento-ingress-policy
  namespace: magento-ns
spec:
  podSelector:
    matchLabels:
      app: magento
  policyTypes:
  - Ingress
  ingress:
  - from:
    ports:
    - protocol: TCP
      port: 8080
