apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  namespace: magento-ns
  name: frontend-certificate
spec:
  domains:
    - kzkiq.com
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  namespace: magento-ns
  name: admin-certificate
spec:
  domains:
    - admin.kzkiq.com
